# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dnb_msgs/ComponentStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ComponentStatus(genpy.Message):
  _md5sum = "3edf5da01aa562198fec3c468cecb80b"
  _type = "dnb_msgs/ComponentStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# component id; it must be unique among all registered components
# @TODO: use on one topic and identify by id
#string component_id

# the official status id of the component
# possible values are
int8 INITIALIZED = 0
int8 STOPPED = 1
int8 RUNNING = 2
int8 CONFIG_NEEDED = 3
int8 ERROR = 4
int8 INTERACTION_REQUEST = 5
int8 DEACTIVATED = 6
int8 status_id

# an individual message for config or error cases
# it should describe the type of needed config or occurred error briefly
# it should be possible to extract automaticly subsequent actions/instructions from the message if this is needed
string status_msg
"""
  # Pseudo-constants
  INITIALIZED = 0
  STOPPED = 1
  RUNNING = 2
  CONFIG_NEEDED = 3
  ERROR = 4
  INTERACTION_REQUEST = 5
  DEACTIVATED = 6

  __slots__ = ['status_id','status_msg']
  _slot_types = ['int8','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       status_id,status_msg

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ComponentStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.status_id is None:
        self.status_id = 0
      if self.status_msg is None:
        self.status_msg = ''
    else:
      self.status_id = 0
      self.status_msg = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.status_id
      buff.write(_get_struct_b().pack(_x))
      _x = self.status_msg
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.status_id,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status_msg = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status_msg = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.status_id
      buff.write(_get_struct_b().pack(_x))
      _x = self.status_msg
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 1
      (self.status_id,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status_msg = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status_msg = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
