// Generated by gencpp from file camera_control_msgs/SetFloatValue.msg
// DO NOT EDIT!


#ifndef CAMERA_CONTROL_MSGS_MESSAGE_SETFLOATVALUE_H
#define CAMERA_CONTROL_MSGS_MESSAGE_SETFLOATVALUE_H

#include <ros/service_traits.h>


#include <camera_control_msgs/SetFloatValueRequest.h>
#include <camera_control_msgs/SetFloatValueResponse.h>


namespace camera_control_msgs
{

struct SetFloatValue
{

typedef SetFloatValueRequest Request;
typedef SetFloatValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFloatValue
} // namespace camera_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_control_msgs::SetFloatValue > {
  static const char* value()
  {
    return "345a3274594e7cc629d8cd38d3b1fe73";
  }

  static const char* value(const ::camera_control_msgs::SetFloatValue&) { return value(); }
};

template<>
struct DataType< ::camera_control_msgs::SetFloatValue > {
  static const char* value()
  {
    return "camera_control_msgs/SetFloatValue";
  }

  static const char* value(const ::camera_control_msgs::SetFloatValue&) { return value(); }
};


// service_traits::MD5Sum< ::camera_control_msgs::SetFloatValueRequest> should match
// service_traits::MD5Sum< ::camera_control_msgs::SetFloatValue >
template<>
struct MD5Sum< ::camera_control_msgs::SetFloatValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::SetFloatValue >::value();
  }
  static const char* value(const ::camera_control_msgs::SetFloatValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::SetFloatValueRequest> should match
// service_traits::DataType< ::camera_control_msgs::SetFloatValue >
template<>
struct DataType< ::camera_control_msgs::SetFloatValueRequest>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::SetFloatValue >::value();
  }
  static const char* value(const ::camera_control_msgs::SetFloatValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_control_msgs::SetFloatValueResponse> should match
// service_traits::MD5Sum< ::camera_control_msgs::SetFloatValue >
template<>
struct MD5Sum< ::camera_control_msgs::SetFloatValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::SetFloatValue >::value();
  }
  static const char* value(const ::camera_control_msgs::SetFloatValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::SetFloatValueResponse> should match
// service_traits::DataType< ::camera_control_msgs::SetFloatValue >
template<>
struct DataType< ::camera_control_msgs::SetFloatValueResponse>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::SetFloatValue >::value();
  }
  static const char* value(const ::camera_control_msgs::SetFloatValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_CONTROL_MSGS_MESSAGE_SETFLOATVALUE_H
