// Generated by gencpp from file camera_control_msgs/SetStringValue.msg
// DO NOT EDIT!


#ifndef CAMERA_CONTROL_MSGS_MESSAGE_SETSTRINGVALUE_H
#define CAMERA_CONTROL_MSGS_MESSAGE_SETSTRINGVALUE_H

#include <ros/service_traits.h>


#include <camera_control_msgs/SetStringValueRequest.h>
#include <camera_control_msgs/SetStringValueResponse.h>


namespace camera_control_msgs
{

struct SetStringValue
{

typedef SetStringValueRequest Request;
typedef SetStringValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetStringValue
} // namespace camera_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::camera_control_msgs::SetStringValue > {
  static const char* value()
  {
    return "43ad6a9b380ac342e4b20e501a2fd46c";
  }

  static const char* value(const ::camera_control_msgs::SetStringValue&) { return value(); }
};

template<>
struct DataType< ::camera_control_msgs::SetStringValue > {
  static const char* value()
  {
    return "camera_control_msgs/SetStringValue";
  }

  static const char* value(const ::camera_control_msgs::SetStringValue&) { return value(); }
};


// service_traits::MD5Sum< ::camera_control_msgs::SetStringValueRequest> should match
// service_traits::MD5Sum< ::camera_control_msgs::SetStringValue >
template<>
struct MD5Sum< ::camera_control_msgs::SetStringValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::SetStringValue >::value();
  }
  static const char* value(const ::camera_control_msgs::SetStringValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::SetStringValueRequest> should match
// service_traits::DataType< ::camera_control_msgs::SetStringValue >
template<>
struct DataType< ::camera_control_msgs::SetStringValueRequest>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::SetStringValue >::value();
  }
  static const char* value(const ::camera_control_msgs::SetStringValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::camera_control_msgs::SetStringValueResponse> should match
// service_traits::MD5Sum< ::camera_control_msgs::SetStringValue >
template<>
struct MD5Sum< ::camera_control_msgs::SetStringValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::camera_control_msgs::SetStringValue >::value();
  }
  static const char* value(const ::camera_control_msgs::SetStringValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::camera_control_msgs::SetStringValueResponse> should match
// service_traits::DataType< ::camera_control_msgs::SetStringValue >
template<>
struct DataType< ::camera_control_msgs::SetStringValueResponse>
{
  static const char* value()
  {
    return DataType< ::camera_control_msgs::SetStringValue >::value();
  }
  static const char* value(const ::camera_control_msgs::SetStringValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CAMERA_CONTROL_MSGS_MESSAGE_SETSTRINGVALUE_H
