[package]
name = "my_robot_services"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rosrust = "0.9.7"
rosrust_msg = "0.1.3"
env_logger = "0.9.0"
